import {
  ADD_CATEGORY,
  CATEGOTY_TYPE,
  CANCEL,
  ADD_TRANSACTION,
  STEP_KEY,
  DEFAULT_STEP,
  ADD_ACCOUNT,
} from '@state/consts/state.consts';

export enum KEYBOARD_CANCEL_CALLBACK {
  CANCEL_STEPS = `${CANCEL}_steps`,
}

// CALL_BACKS
export enum CREATE_CATEGORY_TYPE_CALLBACK {
  INCOME = `${CATEGOTY_TYPE}_income`,
  EXPENSE = `${CATEGOTY_TYPE}_expense`,
  TRANSFER = `${CATEGOTY_TYPE}_transfer`,
}

export enum CREATE_CATEGORY_STEPS_CALLBACK {
  ADD_CATEGORY_NAME = `${ADD_CATEGORY}_name`,
  ADD_CATEGORY_TYPE = `${ADD_CATEGORY}_type`,
  ADD_CATEGORY_EMOJI = `${ADD_CATEGORY}_emoji`,
  ADD_CATEGORY_CONFIRM = `${ADD_CATEGORY}_confirm`,
  ADD_CATEGORY_COMMENT = `${ADD_CATEGORY}_comment`,
}

export enum CREATE_TRANSACTION_STEPS_CALLBACK {
  ADD_TRANSACTION_TYPE = `${ADD_TRANSACTION}_type`,
  ADD_TRANSACTION_CATEGORY_TYPE = `${ADD_TRANSACTION}_category_type`,
  ADD_TRANSACTION_ACCOUNT_TYPE = `${ADD_TRANSACTION}_account_type`,
  ADD_TRANSACTION_AMOUNT = `${ADD_TRANSACTION}_amount`,
  ADD_TRANSACTION_CONFIRM = `${ADD_TRANSACTION}_confirm`,
  ADD_TRANSACTION_COMMENT = `${ADD_TRANSACTION}_comment`,
}

export enum CREATE_ACCOUNT_STEPS_CALLBACK {
  ADD_ACCOUNT_NAME = `${ADD_ACCOUNT}_name`,
  ADD_ACCOUNT_CURRENCY = `${ADD_ACCOUNT}_currency`,
  ADD_ACCOUNT_AMOUNT = `${ADD_ACCOUNT}_amount`,
  ADD_ACCOUNT_CONFIRM = `${ADD_ACCOUNT}_confirm`,
  ADD_ACCOUNT_COMMENT = `${ADD_ACCOUNT}_comment`,
}

// STEPS
export enum STATE_STEPS {
  // START, DEFAULT
  DEFAULT = `${STEP_KEY}${DEFAULT_STEP}`,

  // CANCEL
  CANCEL_STEPS = `${STEP_KEY}${KEYBOARD_CANCEL_CALLBACK.CANCEL_STEPS}`,

  //// CATEGORY
  // 1. Выбор типа категории
  ADD_CATEGORY_NAME = `${STEP_KEY}${CREATE_CATEGORY_STEPS_CALLBACK.ADD_CATEGORY_NAME}`,
  // 2. Выбор типа категории
  ADD_CATEGORY_TYPE = `${STEP_KEY}${CREATE_CATEGORY_STEPS_CALLBACK.ADD_CATEGORY_TYPE}`,
  // 3. Выбор эмодзи категории
  ADD_CATEGORY_EMOJI = `${STEP_KEY}${CREATE_CATEGORY_STEPS_CALLBACK.ADD_CATEGORY_EMOJI}`,
  // 4. Подтверждение категории
  ADD_CATEGORY_CONFIRM = `${STEP_KEY}${CREATE_CATEGORY_STEPS_CALLBACK.ADD_CATEGORY_CONFIRM}`,
  // 5. Ввод комментария к категории
  ADD_CATEGORY_COMMENT = `${STEP_KEY}${CREATE_CATEGORY_STEPS_CALLBACK.ADD_CATEGORY_COMMENT}`,

  //// TRANSACTION
  // 1. Выбор типа транзакции
  ADD_TRANSACTION_TYPE = `${STEP_KEY}${CREATE_TRANSACTION_STEPS_CALLBACK.ADD_TRANSACTION_TYPE}`,
  // 2. Выбор категории  транзакции (категория расхода или дохода)
  ADD_TRANSACTION_CATEGORY_TYPE = `${STEP_KEY}${CREATE_TRANSACTION_STEPS_CALLBACK.ADD_TRANSACTION_CATEGORY_TYPE}`,
  // 3. Выбор счета транзакции
  ADD_TRANSACTION_ACCOUNT_TYPE = `${STEP_KEY}${CREATE_TRANSACTION_STEPS_CALLBACK.ADD_TRANSACTION_ACCOUNT_TYPE}`,
  // 4. Выбор суммы транзакции
  ADD_TRANSACTION_AMOUNT = `${STEP_KEY}${CREATE_TRANSACTION_STEPS_CALLBACK.ADD_TRANSACTION_AMOUNT}`,
  // 5. Подтверждение транзакции
  ADD_TRANSACTION_CONFIRM = `${STEP_KEY}${CREATE_TRANSACTION_STEPS_CALLBACK.ADD_TRANSACTION_CONFIRM}`,
  // 5. Ввод комментария к транзакции
  ADD_TRANSACTION_COMMENT = `${STEP_KEY}${CREATE_TRANSACTION_STEPS_CALLBACK.ADD_TRANSACTION_COMMENT}`,

  //// ACCOUNT
  // 1. Выбор типа счета
  ADD_ACCOUNT_NAME = `${STEP_KEY}${CREATE_ACCOUNT_STEPS_CALLBACK.ADD_ACCOUNT_NAME}`,
  // 2. Выбор типа счета
  ADD_ACCOUNT_CURRENCY = `${STEP_KEY}${CREATE_ACCOUNT_STEPS_CALLBACK.ADD_ACCOUNT_CURRENCY}`,
  // 3. Набор суммы счета
  ADD_ACCOUNT_AMOUNT = `${STEP_KEY}${CREATE_ACCOUNT_STEPS_CALLBACK.ADD_ACCOUNT_AMOUNT}`,
  // 4. Подтверждение счета
  ADD_ACCOUNT_CONFIRM = `${STEP_KEY}${CREATE_ACCOUNT_STEPS_CALLBACK.ADD_ACCOUNT_CONFIRM}`,
  // 5. Ввод комментария к счету
  ADD_ACCOUNT_COMMENT = `${STEP_KEY}${CREATE_ACCOUNT_STEPS_CALLBACK.ADD_ACCOUNT_COMMENT}`,
}
