import {
  ADD_CATEGORY,
  CATEGOTY_TYPE,
  CANCEL,
  ADD_TRANSACTION,
  STEP_KEY,
  DEFAULT_STEP,
} from '@state/consts/state.consts';

export enum KEYBOARD_CANCEL_CALLBACK {
  CANCEL_STEPS = `${CANCEL}_steps`,
}

// CALL_BACKS
export enum CREATE_CATEGORY_TYPE_CALLBACK {
  INCOME = `${CATEGOTY_TYPE}_income`,
  EXPENSE = `${CATEGOTY_TYPE}_expense`,
  TRANSFER = `${CATEGOTY_TYPE}_transfer`,
}

export enum CREATE_CATEGORY_STEPS_CALLBACK {
  ADD_CATEGORY_NAME = `${ADD_CATEGORY}_name`,
  ADD_CATEGORY_TYPE = `${ADD_CATEGORY}_type`,
  ADD_CATEGORY_EMOJI = `${ADD_CATEGORY}_emoji`,
}

export enum CREATE_TRANSACTION_STEPS_CALLBACK {
  ADD_TRANSACTION_TYPE = `${ADD_TRANSACTION}_type`,
  ADD_TRANSACTION_CATEGORY_TYPE = `${ADD_TRANSACTION}_category_type`,
  ADD_TRANSACTION_AMOUNT = `${ADD_TRANSACTION}_amount`,
  ADD_TRANSACTION_CONFIRM = `${ADD_TRANSACTION}_confirm`,
}

// STEPS
export enum STATE_STEPS {
  // START, DEFAULT
  DEFAULT = `${STEP_KEY}${DEFAULT_STEP}`,

  // CANCEL
  CANCEL_STEPS = `${STEP_KEY}${KEYBOARD_CANCEL_CALLBACK.CANCEL_STEPS}`,

  //// CATEGORY
  // 1. Выбор типа категории
  ADD_CATEGORY_NAME = `${STEP_KEY}${CREATE_CATEGORY_STEPS_CALLBACK.ADD_CATEGORY_NAME}`,
  // 2. Выбор типа категории
  ADD_CATEGORY_TYPE = `${STEP_KEY}${CREATE_CATEGORY_STEPS_CALLBACK.ADD_CATEGORY_TYPE}`,
  // 3. Выбор эмодзи категории
  ADD_CATEGORY_EMOJI = `${STEP_KEY}${CREATE_CATEGORY_STEPS_CALLBACK.ADD_CATEGORY_EMOJI}`,

  //// TRANSACTION
  // 1. Выбор типа транзакции
  ADD_TRANSACTION_TYPE = `${STEP_KEY}${CREATE_TRANSACTION_STEPS_CALLBACK.ADD_TRANSACTION_TYPE}`,
  // 2. Выбор категории транзакции
  ADD_TRANSACTION_CATEGORY_TYPE = `${STEP_KEY}${CREATE_TRANSACTION_STEPS_CALLBACK.ADD_TRANSACTION_CATEGORY_TYPE}`,
  // 3. Выбор суммы транзакции
  ADD_TRANSACTION_AMOUNT = `${STEP_KEY}${CREATE_TRANSACTION_STEPS_CALLBACK.ADD_TRANSACTION_AMOUNT}`,
  // 4. Подтверждение транзакции
  ADD_TRANSACTION_CONFIRM = `${STEP_KEY}${CREATE_TRANSACTION_STEPS_CALLBACK.ADD_TRANSACTION_CONFIRM}`,
}
